### ISSUE TITLE
nextjs with amplify for s3 storage

### ISSUE THREAD

**Issue by kisaragiRY** [kisaragiRY/PracticeProjects#7]
# nextjs with amplify for s3 storage
- pages:
  - Home: `/`
  - Blog: `/blog`
  - Blog page: `/blog/[id]`
- lambda -> S3 
- `/4-nextjs-with-amplify-for-s3-storage/`

**Comment by Kisaragi-atwork** [comment]
# using `getStaticProps` and `getStaticPaths` for routing
## example
```jsx
// pages/[slug].js
import { S3 } from 'aws-sdk';

const s3 = new S3();

export async function getStaticPaths() {
  // Fetch the list of all blog post slugs from S3
  const s3Response = await s3.listObjectsV2({ Bucket: 'your-s3-bucket' }).promise();
  const paths = s3Response.Contents.map((item) => ({
    params: { slug: item.Key.replace(/\.md$/, '') },
  }));

  return { paths, fallback: 'blocking' };
}

export async function getStaticProps({ params }) {
  // Fetch data for the specific blog post from S3
  const s3Response = await s3.getObject({ Bucket: 'your-s3-bucket', Key: `${params.slug}.md` }).promise();
  const content = s3Response.Body.toString();

  return {
    props: {
      post: {
        title: 'Your Title', // Extract title from content or metadata
        content,
      },
    },
    revalidate: 60,
  };
}

```

**Comment by kisaragiRY** [comment]
# deploy with serverless
- protect apigateway
  - [Serverless Framework の API Gateway Authorizer 実装を解説します！](https://www.ragate.co.jp/blog/articles/5024)
- deploy with serverless

**Comment by Kisaragi-atwork** [comment]
# using existing resources in amplify
- [AWS Amplify: Using Existing Auth and API Resources](https://dev.to/focusotter/aws-amplify-using-existing-auth-and-api-resources-30pg)

**Comment by Kisaragi-atwork** [comment]
# serverless settings for cognito related resources
- [ref](https://vgaltes.com/post/cognito-user-pools-google/)

**Comment by Kisaragi-atwork** [comment]
# connect frontend to the api
